services:
  java:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container-java
    working_dir: /workspace
    volumes:
      - ./src:/workspace/src
    stdin_open: true
    tty: true
